# Generated by Django 5.1 on 2026-05-25 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizApp', '0002_empresa_usuario_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['usuario_log', 'nombre'], name='empresa_user_nombre_idx'),
        ),
    ]
