# Generated by Django 5.1 on 2025-07-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='proyectoWeb/media/articulos/sin imagen.jpg', null=True, upload_to='articulos'),
        ),
    ]
