# Generated by Django 5.1 on 2025-08-09 19:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, default='sin_imagen_opeh5q', max_length=255, null=True, verbose_name='image'),
        ),
    ]
