# Generated by Django 5.1 on 2026-05-25 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_alter_articulo_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['usuario_log', 'nombre'], name='articulo_user_nombre_idx'),
        ),
    ]
