# Generated by Django 5.0.1 on 2024-06-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacionApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articulos',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
        migrations.DeleteModel(
            name='Cotizaciones',
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
    ]
