# Generated by Django 5.1 on 2024-12-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturacionApp', '0002_delete_articulos_delete_clientes_delete_cotizaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='logo',
        ),
    ]
