# Generated by Django 5.1 on 2025-07-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cuit',
            field=models.CharField(default=444444444, max_length=20),
            preserve_default=False,
        ),
    ]
