# Generated by Django 5.1 on 2026-05-25 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientes_cuit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['usuario_log', 'nombre'], name='cliente_user_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='clientes',
            index=models.Index(fields=['usuario_log', 'nombre_empresa'], name='cliente_user_empresa_idx'),
        ),
    ]
