# Generated by Django 5.1 on 2025-06-17 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientes_usuario_log'),
        ('cotizaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='cliente',
            field=models.ManyToManyField(to='clientes.clientes'),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='numero_referencia',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
