# Generated by Django 5.1 on 2025-08-14 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_alter_articulo_imagen'),
        ('cotizaciones', '0002_alter_cotizaciones_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='articuloscotizado',
            name='articulo_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articuloscotizado',
            name='articulo_nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='articuloscotizado',
            name='articulo_precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='empresa_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='articuloscotizado',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articulos.articulo'),
        ),
    ]
