# Generated by Django 5.0.1 on 2024-07-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_rename_articulos_articulo'),
        ('clientes', '0001_initial'),
        ('cotizaciones', '0002_alter_cotizaciones_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizaciones',
            name='total_cotizado',
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='articulos_cotizados',
            field=models.ManyToManyField(to='articulos.articulo'),
        ),
        migrations.RemoveField(
            model_name='cotizaciones',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='cliente',
            field=models.ManyToManyField(null=True, to='clientes.clientes'),
        ),
    ]
