# Generated by Django 5.1 on 2025-06-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizaciones_usuario_alter_cotizaciones_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='condiciones_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
