# Generated by Django 5.1 on 2025-06-17 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientes_usuario_log'),
        ('cotizaciones', '0003_cotizaciones_condiciones_pago_cotizaciones_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizaciones',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes'),
            preserve_default=False,
        ),
    ]
