# Generated by Django 5.1 on 2025-08-14 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_articuloscotizado_articulo_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='cliente_cuit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='cliente_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='cliente_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='empresa_cuit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='empresa_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='empresa_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cotizaciones',
            name='empresa_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
