# Generated by Django 5.1 on 2026-05-25 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientes_cliente_user_nombre_idx_and_more'),
        ('cotizApp', '0003_empresa_empresa_user_nombre_idx'),
        ('cotizaciones', '0004_cotizaciones_cliente_cuit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cotizaciones',
            index=models.Index(fields=['usuario', '-created'], name='cotiz_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizaciones',
            index=models.Index(fields=['usuario', 'numero_referencia'], name='cotiz_user_ref_idx'),
        ),
    ]
