# Generated by Django 5.1 on 2025-06-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_remove_cotizaciones_cliente_cotizaciones_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='cotizaciones_pdfs/'),
        ),
    ]
