# Generated by Django 5.1 on 2025-06-18 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_cotizaciones_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizaciones',
            name='pdf',
        ),
    ]
