# Generated by Django 5.1 on 2025-06-18 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_alter_articulo_usuario_log'),
        ('cotizaciones', '0006_remove_cotizaciones_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizaciones',
            name='articulos_cotizados',
        ),
        migrations.CreateModel(
            name='ArticulosCotizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulos.articulo')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.cotizaciones')),
            ],
        ),
    ]
