# Generated by Django 5.1 on 2025-06-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0007_remove_cotizaciones_articulos_cotizados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='total_con_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
