# Generated by Django 5.1 on 2025-06-19 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0008_cotizaciones_total_cotizaciones_total_con_descuento'),
        ('facturacionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacionApp.empresa'),
        ),
    ]
