# Generated by Django 5.1 on 2025-06-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0009_cotizaciones_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='costo_envio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
