# Generated by Django 5.1 on 2025-07-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0010_cotizaciones_costo_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
