# Generated by Django 5.1 on 2025-07-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0011_cotizaciones_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizaciones',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
