# Generated by Django 5.1 on 2025-07-04 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0012_alter_cotizaciones_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articuloscotizado',
            name='subtotal',
        ),
    ]
