# Generated by Django 5.1 on 2025-07-04 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0013_remove_articuloscotizado_subtotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizaciones',
            options={},
        ),
    ]
